version: "3.1"

services:
  rabbitmq:
    restart: always
    hostname: rabbitmq
    image: rabbitmq:3.11.9-management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 1s
      retries: 5

  worker:
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TON_REPO: https://github.com/ton-blockchain/ton
        TON_BRANCH: master
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    secrets:
      - private_key
      - public_key

volumes:
  rabbitmq:

secrets:
  private_key:
    file: private/client
  public_key:
    file: private/server.pub
